chain:
  rpc:
    - "https://endpoints.omniatech.io/v1/eth/goerli/public"
  addr:
    - "0x2fAD18285F4192A130752030D07fA39f9923Ad16"
redis:
  addr: "120.25.239.33:7069"
  password: "123456"
  db: "1"
mq:
  url: "amqp://admin:admin@123456@120.25.239.33:7072/"
  exchange: "ngp-exchange"
  key: "ngp-key"
  queue: "ngp-queue"
